### ISSUE TITLE
邮箱地址包含大写字母，验证无法通过

### ISSUE THREAD

**Issue by zhengzhp** [jaywcjlove/validator.js#24]
`isEmail`函数无法正确验证有大写字母的输入

现在的email校验正则 ` /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/`

**rickharrison/validate.js** 现在使用的正则
```/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/```

**Comment by zhengzhp** [comment]
当我没提过这个问题，你竟然还单独修改了限制

**Comment by jaywcjlove** [comment]
@zhengzhp 你可以自定义正则使用。

**Comment by zhengzhp** [comment]
@jaywcjlove 已经修改了，我还以为这是个bug，没想到你就是想要这么一个效果
