### ISSUE TITLE
是不是挺多变量声明之后没有用到？

### ISSUE THREAD

**Issue by jsonz1993** [jaywcjlove/validator.js#7]
比如说 `this.handles["ok"] = true;` 比如说 `this.isCallback`  只是看了两遍，没发现有用到，不是很明白写在那里的用意

**Comment by jsonz1993** [comment]
而且 _validateField 循环里面的 `j`变量....好像没有声明直接就使用了

```
                for (j = 0; j < this.errors.length; j += 1) {
                    if (field.element === this.errors[j].element) {
                        existingError = this.errors[j];
                    }
                }
```

**Comment by jaywcjlove** [comment]
`this.isCallback` 下面这一句 [#L85](https://github.com/jaywcjlove/validator.js/blob/master/src/validator.js#L85) 这里判断了这个就没有用了，冗余了。

```js
this.handles["ok"] = true;
this.handles["evt"] = evt;
```
这种是有用的，在回调里面可以做一些判断 [#L146](https://github.com/jaywcjlove/validator.js/blob/master/src/validator.js#L146)

而且 `_validateField` 循环里面的 `j` 变量，这里面是在浏览器里面不报错的，这种写法叫隐式的将`j`声明为全局变量。我经常拿这个考面试者，但是这种习惯十分不好，不便于阅读理解，应该是我忘记了吧。😂😂

```js
for (j = 0; j < this.errors.length; j += 1) {
// ....
}
```

**Comment by jsonz1993** [comment]
我的天！大佬 原来可以直接连接到code。 正在看代码 挺赞的。这个issues先留两天吧，我这两天看代码，如果有什么疑问再上来问大佬

**Comment by jaywcjlove** [comment]
@jsonz1993 勤奋的好孩子，这个代码很利于你学习js基础。

我的这两个小玩意儿，也是学习的小例子

[store.js](https://github.com/jaywcjlove/store.js)   
[cookie.js](https://github.com/jaywcjlove/cookie.js)

**Comment by jsonz1993** [comment]
start 了。表单验证这块，因为公司用的是es6语法，所以重新封装了一次。 后面使用一段时间再分享出来
